[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.2.0"

[[constraint]]
  name = "github.com/go-kit/kit"
  revision = "fadad6fffe0466b19df9efd9acde5c9a52df5fa4"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.3.0"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.0"

[prune]
  go-tests = true
  unused-packages = true
